### ISSUE TITLE
[✍️ Dev Log] FE 정재혁 / 2022-01-12 

### ISSUE THREAD

**Issue by Esoolgnah** [codestates/ALL-CON#178]
### 오늘은 어떻게 프로젝트에 기여했나요?
- 헤더에 마우스 호버 시 크롤링 남은시간 표시
- 콘친인증페이지, 프로필 수정 페이지 등 인풋창 width 조절
- footerWrapper 사이즈 정비
- 모바일, 탭사이즈 사이드메뉴 드랍 다운 제작
    - 헤더 타이머 처음엔 상단 고정, 스크롤 내리면 그 다음부터  호버시 보여지게 수정
    - 스크롤 위치 전역관리 설정 (headerSlice ⇒ scrollCount)
- 프로필이미지 아이콘 마우스 호버 시 드랍다운 모달 제작

### 오늘의 프로젝트에서 힘든 점은 무엇인가요?

- 머지할 때 내가 설정했던 것들이 달라져서 들어오는 경우 때문에 다시 수정할때 조금 힘들었던 것 같다.
- 헤더 타이머를 구현할 때 그냥 나오는게 조금 심심해보여 transition 속성으로 애니메이션을 추가해보았는데 잘 들어맞았다.
다른 부분에서도 호버시마다 변경사항과 함께 적절하게 적용해주면 괜찮을 것 같다. 

```scss
  #hiddenBar {
   .....
    transition: 0.25s all;
    // 본체에 넣으면 돌아오는 부분 애니메이션이 된다. 
    &:hover {
   .......
      transition: 0.5s all;
     // 0.5초 동안 변화애니메이션 실행
      }
  }
```

### 내일은 프로젝트에 기여하기 위해 무엇을 해야 하나요?

- [ ] 콘친 페이지 기능 구현
